-- ============================================================
-- Urbanshop schema
-- Run this whole file once in the Supabase SQL Editor.
-- Safe to re-run: every statement uses "if not exists" / "or replace"
-- / "on conflict do nothing" where possible.
-- ============================================================

create extension if not exists "uuid-ossp";

-- ---------- Core tables ----------

create table if not exists profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text,
    email text,
    role text not null default 'user' check (role in ('user', 'admin')),
    created_at timestamptz default now()
);

-- Add the email column if this schema was run before it existed.
alter table profiles add column if not exists email text;

create table if not exists categories (
    id bigint generated by default as identity primary key,
    name text unique not null
);

create table if not exists products (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    price numeric(12,2) not null,
    category text,
    category_id bigint references categories(id),
    location text,
    images jsonb default '[]'::jsonb,
    image_url text,
    reseller_link text default '',
    is_active boolean default true,
    created_by uuid references profiles(id),
    created_at timestamptz default now()
);

-- Add new columns to products if they are missing (safe to re-run).
alter table products add column if not exists category text;
alter table products add column if not exists image_url text;
alter table products alter column reseller_link set default '';

create table if not exists wishlist (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade,
    product_id bigint references products(id) on delete cascade,
    created_at timestamptz default now(),
    unique (user_id, product_id)
);

create table if not exists addresses (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade,
    line1 text not null,
    line2 text,
    city text not null,
    state text not null,
    pincode text not null,
    is_default boolean default false
);

create table if not exists analytics_events (
    id bigint generated by default as identity primary key,
    event_type text not null check (event_type in ('page_view', 'product_view', 'reseller_click')),
    product_id bigint references products(id) on delete set null,
    user_id uuid references auth.users(id) on delete set null,
    created_at timestamptz default now()
);

insert into categories (name)
values
    ('T-Shirts'), ('Shirts'), ('Jeans'), ('Hoodies'), ('Pants'),
    ('Dresses'), ('Jackets'), ('Shoes'), ('Hats'),
    ('Smartphones'), ('Laptops'), ('Headphones'), ('Tablets'), ('Cameras'), ('Smart Watches'),
    ('Furniture'), ('Kitchen'), ('Home Decor'), ('Appliances'), ('Bedding'),
    ('Books'), ('Sports'), ('Beauty'), ('Toys'), ('Grocery'),
    ('Automotive'), ('Gardening'), ('Jewelry'), ('Bags'), ('Sunglasses')
on conflict (name) do nothing;

-- ---------- Seed products ----------
insert into products (title, category, price, location, image_url)
values
    ('Oversized Black T-Shirt', 'T-Shirts', 799, 'Pune', null),
    ('Premium White Shirt', 'Shirts', 1299, 'Mumbai', null),
    ('Relaxed Fit Blue Jeans', 'Jeans', 1799, 'Delhi', null)
on conflict do nothing;

-- ---------- Auto-create a profile row whenever someone signs up ----------
-- Also copies their email into profiles so the admin Users page can show it
-- (auth.users isn't readable from the client, profiles is).

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, full_name, email, role)
    values (
        new.id,
        coalesce(new.raw_user_meta_data->>'full_name', ''),
        new.email,
        'user'
    );
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();

-- ---------- Admin check helper ----------
-- security definer lets this bypass RLS internally so policies that call it
-- don't recursively re-trigger the RLS check on profiles.

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
    select exists (
        select 1 from public.profiles
        where id = auth.uid() and role = 'admin'
    );
$$;

-- ---------- Row Level Security ----------

alter table profiles enable row level security;
alter table categories enable row level security;
alter table products enable row level security;
alter table wishlist enable row level security;
alter table addresses enable row level security;
alter table analytics_events enable row level security;

-- profiles: users see/update their own row, admins see/update everyone's
drop policy if exists "profiles_select_own" on profiles;
create policy "profiles_select_own" on profiles for select
    using (auth.uid() = id);

drop policy if exists "profiles_select_admin" on profiles;
create policy "profiles_select_admin" on profiles for select
    using (public.is_admin());

drop policy if exists "profiles_update_own" on profiles;
create policy "profiles_update_own" on profiles for update
    using (auth.uid() = id)
    with check (auth.uid() = id);

drop policy if exists "profiles_update_admin" on profiles;
create policy "profiles_update_admin" on profiles for update
    using (public.is_admin());

-- Belt-and-braces: even though the admin Users page is the only intended
-- place role changes happen, this trigger stops a non-admin from ever
-- promoting themselves by silently reverting any role change they attempt.
create or replace function public.prevent_role_self_escalation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if new.role is distinct from old.role and not public.is_admin() then
        new.role := old.role;
    end if;
    return new;
end;
$$;

drop trigger if exists profiles_guard_role on profiles;

create trigger profiles_guard_role
    before update on profiles
    for each row execute function public.prevent_role_self_escalation();

-- categories: readable by everyone, writable by admins only
drop policy if exists "categories_select_all" on categories;
create policy "categories_select_all" on categories for select
    using (true);

drop policy if exists "categories_write_admin" on categories;
create policy "categories_write_admin" on categories for all
    using (public.is_admin())
    with check (public.is_admin());

-- products: public sees active products, admins see/manage everything
drop policy if exists "products_select_active" on products;
create policy "products_select_active" on products for select
    using (is_active = true);

drop policy if exists "products_select_admin" on products;
create policy "products_select_admin" on products for select
    using (public.is_admin());

drop policy if exists "products_write_admin" on products;
create policy "products_write_admin" on products for all
    using (public.is_admin())
    with check (public.is_admin());

-- wishlist: each user manages only their own rows
drop policy if exists "wishlist_owner" on wishlist;
create policy "wishlist_owner" on wishlist for all
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

-- addresses: each user manages only their own rows
drop policy if exists "addresses_owner" on addresses;
create policy "addresses_owner" on addresses for all
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

-- analytics_events: anyone (including anonymous visitors) can log an event,
-- only admins can read them back
drop policy if exists "analytics_insert_any" on analytics_events;
create policy "analytics_insert_any" on analytics_events for insert
    with check (true);

drop policy if exists "analytics_select_admin" on analytics_events;
create policy "analytics_select_admin" on analytics_events for select
    using (public.is_admin());

-- ---------- Storage: product images ----------

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

drop policy if exists "product_images_public_read" on storage.objects;
create policy "product_images_public_read" on storage.objects for select
    using (bucket_id = 'product-images');

drop policy if exists "product_images_admin_write" on storage.objects;
create policy "product_images_admin_write" on storage.objects for insert
    with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "product_images_admin_update" on storage.objects;
create policy "product_images_admin_update" on storage.objects for update
    using (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "product_images_admin_delete" on storage.objects;
create policy "product_images_admin_delete" on storage.objects for delete
    using (bucket_id = 'product-images' and public.is_admin());

-- ---------- Making your first admin ----------
-- 1. Sign up once through the app (this creates your auth.users + profiles row).
-- 2. In the SQL Editor, run (swap in your email):
--    update profiles set role = 'admin' where email = 'you@example.com';
